Repository ROBOTIS-move/labelme, pull requests merged in 2022-05, with the labels that each got.

#1 Modified labelme for labeling by ROBOTIS algorithm team
  .gitignore
  CHANGELOG.rst
  labelme/__main__.py
  labelme/app.py
  labelme/cli/__init__.py
  labelme/cli/class.yaml
  labelme/cli/draw_object_label.py
  labelme/cli/draw_segment_label.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  labelme/label_file.py
  labelme/utils/__init__.py
  labelme/utils/draw.py
  package.xml
  set_labelme_environment.sh
Labels: enhancement

#2 Fixed saving errors
  labelme/app.py
  labelme/label_file.py
  setup.py
Labels: bug

#3 Modified label masking function
  labelme/cli/draw_segment_label.py
  labelme/utils/__init__.py
  labelme/utils/_io.py
Labels: bug

#5 Changed matplotlib version and default label colors
  labelme/app.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  setup.py
Labels: enhancement

#6 Added mode selection function for add point to edge
  labelme/app.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  labelme/widgets/canvas.py
Labels: enhancement

#7 Modified cursor shape
  labelme/widgets/canvas.py
Labels: enhancement

#8 Bump to 4.1.0
  .gitignore
  CHANGELOG.rst
  labelme/__main__.py
  labelme/app.py
  labelme/cli/__init__.py
  labelme/cli/class.yaml
  labelme/cli/draw_object_label.py
  labelme/cli/draw_segment_label.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  labelme/label_file.py
  labelme/utils/__init__.py
  labelme/utils/_io.py
  labelme/utils/draw.py
  labelme/widgets/canvas.py
  package.xml
  set_labelme_environment.sh
  setup.py
Labels: bump :rocket:
