Repository ROBOTIS-move/labelme, pull requests merged in 2022-07, with the labels that each got.

#22 Added single class mode
  labelme/app.py
  labelme/config/default_config.yaml
Labels: enhancement

#21 Added category for elevator button segmentation
  labelme/app.py
  labelme/cli/class.yaml
  labelme/cli/draw_object_label.py
  labelme/cli/draw_segment_label.py
  labelme/config/default_config.yaml
  labelme/label_file.py
Labels: enhancement

#23 Added new detection class
  labelme/cli/class.yaml
  labelme/config/default_config.yaml
Labels: enhancement

#25 Modified moving label function in edit mode
  labelme/shape.py
  labelme/widgets/canvas.py
Labels: bug, enhancement

#26 Bump to 4.3.0
  CHANGELOG.rst
  labelme/app.py
  labelme/cli/class.yaml
  labelme/cli/draw_object_label.py
  labelme/cli/draw_segment_label.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  labelme/icons/redo.png
  labelme/label_file.py
  labelme/shape.py
  labelme/widgets/canvas.py
  package.xml
Labels: bump :rocket:

#29 Changed drawing line color and color visualization rules
  labelme/app.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
Labels: bug, enhancement

#32 Added shortcuts for hide and show all
  labelme/app.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  labelme/widgets/canvas.py
Labels: bug, enhancement

#36 Modified segmentation label conversion codes
  labelme/cli/class.yaml
  labelme/cli/draw_segment_label.py
  labelme/utils/draw.py
Labels: enhancement

#39 Modified a popup position and Fixed a intersection point bug
  labelme/app.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  labelme/widgets/canvas.py
  labelme/widgets/label_dialog.py
Labels: bug, enhancement
