Repository ROBOTIS-move/labelme, pull requests merged in 2022-11, with the labels that each got.

#53 Modified administrator functions
  labelme/app.py
  labelme/cli/draw_object_label.py
  labelme/cli/draw_segment_label.py
  labelme/widgets/__init__.py
  labelme/widgets/convert_label_popup.py
  labelme/widgets/image_popup.py
Labels: enhancement

#55 Added useful functions for detection labeling
  labelme/app.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  labelme/widgets/canvas.py
  set_labelme_environment.sh
Labels: enhancement, proposal

#56 Added exception handling
  labelme/widgets/canvas.py
Labels: bug, enhancement

#59 Added function to reset to previous brightness and contrast
  labelme/app.py
  labelme/config/default_config.yaml
Labels: enhancement

#57 Added probabillity value
  labelme/app.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  labelme/label_file.py
  labelme/shape.py
Labels: enhancement

#61 Modified CHANGELOG.rst
  CHANGELOG.rst
Labels: bump :rocket:

#60 Bump to 4.7.0
  CHANGELOG.rst
  labelme/app.py
  labelme/cli/draw_object_label.py
  labelme/cli/draw_segment_label.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  labelme/label_file.py
  labelme/shape.py
  labelme/widgets/__init__.py
  labelme/widgets/canvas.py
  labelme/widgets/convert_label_popup.py
  labelme/widgets/image_popup.py
  package.xml
  set_labelme_environment.sh
Labels: bump :rocket:
