Repository ROBOTIS-move/labelme, pull requests merged in 2022-06, with the labels that each got.

#11 Added multiprocessing of segmentation converter
  labelme/cli/draw_segment_label.py
Labels: enhancement

#12 Modified process core
  labelme/cli/draw_segment_label.py
Labels: bug, enhancement

#14 Bump to 4.2.0
  CHANGELOG.rst
  labelme/cli/class.yaml
  labelme/cli/draw_segment_label.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  package.xml
Labels: bump :rocket:

#16 Added redo function
  labelme/app.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  labelme/icons/redo.png
  labelme/widgets/canvas.py
Labels: enhancement

#18 Added exception handling of auto save mode
  labelme/app.py
  labelme/config/default_config.yaml
Labels: bug, enhancement

#20 Added useful functions for bounding box labeling
  labelme/app.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  labelme/shape.py
  labelme/widgets/canvas.py
Labels: enhancement
