Repository ROBOTIS-move/labelme, pull requests merged in 2022-09, with the labels that each got.

#45 Added exception handling and parameter keeping mode
  labelme/app.py
  labelme/config/__init__.py
  labelme/config/default_config.yaml
Labels: bug, enhancement

#46 Added a new segmentation class
  labelme/cli/class.yaml
  labelme/config/__init__.py
  labelme/config/default_config.yaml
Labels: enhancement

#47 Bump to 4.5.0
  CHANGELOG.rst
  labelme/app.py
  labelme/cli/class.yaml
  labelme/config/__init__.py
  labelme/config/default_config.yaml
  package.xml
Labels: bump :rocket:
